### PR TITLE
Migrating all resonance-audio documentation to GitHub

### PR DESCRIPTION
**Pull request by claywilkinson**
This moves all pages from https://developers.google.com/resonance-audio/ to GitHub.

Templates and style sheets have been added to mostly match the devsite layout and format.  Most notably is the change from a top menu  to a side menu.  This was done for simplicity.  The menu and default layout were reused from https://github.com/google/ExoPlayer/tree/gh-pages - published at
https://google.github.io/ExoPlayer/guide.html 

Staged at 
https://claywilkinson.github.io/resonance-audio/

### CODE REVIEW

**Comment by jkammerl** [comment]
Great! In Chrome, it appears that the margins between the navigation and the site are all set to zero:
image
Can this be easily fixed?

**Comment by claywilkinson** [comment]
Thanks for the feedback! Yes, I have fixed the layout of the menu so it looks better then is hidden as the window gets too small.

**Comment by mgorzel** [comment]
Thanks Clayton!

Some section titles seem to be repeated, for example: https://claywilkinson.github.io/resonance-audio/reference/fmod/ or https://claywilkinson.github.io/resonance-audio/develop/vst-monitor/getting-started.html. Could we maybe unify all the section titles to look like in https://claywilkinson.github.io/resonance-audio/develop/web/getting-started.html or https://claywilkinson.github.io/resonance-audio/develop/wwise/getting-started.html and remove all the "Get started / Getting started" text?

Also, on the main page please correct the link wWise -> Wwise.

**Comment by claywilkinson** [comment]
@mgorzel  - Thanks for feedback.  Please take a look.  I organized the links and made  sub-headings for "Getting Started" and "Reference" which cleaned it up.

**Comment by mgorzel** [comment]
Looks great, thanks Clayton!

Could we also remove the 'Getting started...' subtitles from:

https://claywilkinson.github.io/resonance-audio/develop/vst-monitor/getting-started.html
https://claywilkinson.github.io/resonance-audio/develop/web/getting-started.html &
https://claywilkinson.github.io/resonance-audio/develop/wwise/getting-started.html ?

Thanks!

**Comment by claywilkinson** [comment]
Updated those pages.  Thanks!

**Comment by claywilkinson** [comment]
Hi @anokta & @haroonq  - Friendly ping post-holidays - Can we continue to get this merged?  Thanks!

**Review by haroonq — APPROVED** [review]

**Comment by claywilkinson** [comment]
Thanks for the approval @haroonq  - Can you merge this PR so I can start updating devsite to point to here for the Resonance Audio content?

**Pull request merged**
